- job:
    name: k1s-tox-py39
    run: playbooks/k1s-tox-py39.yaml
    nodeset:
      nodes:
        - name: testrunner
          label: cloud-centos-9-stream


- project:
    check:
      jobs:
        - k1s-tox-py39
        - tox-pep8:
            voting: yes
            nodeset:
              nodes:
                - name: testrunner
                  label: cloud-centos-9-stream
    gate:
      jobs:
        - k1s-tox-py39
        - tox-pep8:
            voting: yes
            nodeset:
              nodes:
                - name: testrunner
                  label: cloud-centos-9-stream
    periodic:
      jobs:
        - k1s-tox-py39